# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Who is ChainLynx?"

# The text below the title.
about: >
  ChainLynx 8248 is a **FIRST Robotics team** based at Lincoln High School, committed to providing a fun and collaborative environment for students to learn how to design, build, and code robots.
  Through ChainLynx, students gain skills in CAD (Computer Aided Design) software, tool use, business, and leadership that will prepare them for future careers.

# The pictures in the image carousel.
#  The description is shown when the user hovers over the image.
#  The url is the file path relative to the 'public' folder.
pictures:
  - desc: "Our 2025 robot, Just Todd at the Sammamish District Event"
    url: "/imgs/index/JustTodd.JPG"
  - desc: "Loading the robot onto the field at the 2024 Girls Gen competition"
    url: "/imgs/index/DSC06805.webp"
  - desc: "ChainLynx members strategizing in the pit"
    url: "/imgs/index/DSC06838.webp"
  - desc: "Gayboys scouting the matches at Girls Gen"
    url: "/imgs/index/DSC06778.webp"
  - desc: "Seniors at Sammimish 2024 celebrating their last competition"
    url: "/imgs/index/ED102472.webp"
  - desc: "All of ChainLynx's awards"
    url: "/imgs/index/ChainLynx Awards!.png"
  - desc: "Chainlynx 2024 Glacier Peak pit"
    url: "/imgs/index/Glacierpeakpit.jpg"
  - desc: "Kickoff of the 2024 CRESCENDO competition"
    url: "/imgs/index/ED101995.jpg"
  - desc: "Strategizing for the 2024 CRESCENDO competition"
    url: "/imgs/index/DSC_1073.JPG"
  - desc: "Pit crew during Bordie Charged 2023"
    url: "/imgs/index/pit_crew_bordie_charged_2023.jpg"
  - desc: "Our robot, 8248, prepared to compete during Bordie Charged 2023"
    url: "/imgs/index/ED101340.jpg"
  - desc: "ChainLynx team members preparing the robot during Bordie Charged 2023"
    url: "/imgs/index/Scan100583.jpg"
  - desc: "Making a quick repair during the Sammamish District Event 2023"
    url: "/imgs/index/DSC_5003.JPG"
  - desc: "Building of the robot during the 2021-2022 season"
    url: "/imgs/index/robot4.jpg"
  

plz_donate: >
  As a student-run team, we rely on donations and [sponsors](/sponsors) to run. 
  Please consider donating to ChainLynx 8248 to help us continue to provide a 
  enriching and educational experience for our members. âœ¨